<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>moinsearch</AssemblyName>
    <RootNamespace>Moinsearch</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <InvariantGlobalization>true</InvariantGlobalization>
    <Version>0.0.2</Version>
    <PublishAot>true</PublishAot>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Tomlyn" Version="2.10.1" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Moinsearch.Tests" />
  </ItemGroup>

</Project>
